# Files to exclude
exclude-files:
  - README.md
  - .gitignore
  - .pre-commit-config.yaml
  - LICENSE

# Add github urls
community-templates:
  - https://gist.github.com/0x240x23elu/29c081552f321ae50fd179c51f4d56da
  - https://gist.github.com/0x240x23elu/67338cc0a71588bca8f1a318a05d67e2
  - https://gist.github.com/0x240x23elu/7b758dc76a9b2bef1a0dc164a9358a15
  - https://gist.github.com/0x240x23elu/c99d44376ffda02b1a4a05a1037cb126
  - https://gist.github.com/0x240x23elu/0d99864c30761d0b80cc6af9e66a6a80
  - https://gist.github.com/ResistanceIsUseless/e46848f67706a8aa1205c9d2866bff31/
  - https://github.com/0x240x23elu/nuclei2021.git
  - https://github.com/wr00t/templates.git
  - https://github.com/0x727/ObserverWard_0x727.git
  - https://github.com/1in9e/my-nuclei-templates.git
  - https://github.com/5cr1pt/templates.git
  - https://github.com/ARPSyndicate/kenzer-templates.git
  - https://github.com/AshiqurEmon/nuclei_templates.git
  - https://github.com/CharanRayudu/Custom-Nuclei-Templates.git
  - https://github.com/clarkvoss/Nuclei-Templates.git
  - https://github.com/d3sca/Nuclei_Templates.git
  - https://github.com/daffainfo/my-nuclei-templates.git
  - https://github.com/esetal/nuclei-bb-templates.git
  - https://github.com/ethicalhackingplayground/erebus-templates.git
  - https://github.com/foulenzer/foulenzer-templates.git
  - https://github.com/geeknik/nuclei-templates-1.git
  - https://github.com/geeknik/the-nuclei-templates.git
  - https://github.com/Harish4948/Nuclei-Templates.git
  - https://github.com/im403/nuclei-temp.git
  - https://github.com/javaongsan/nuclei-templates.git
  - https://github.com/joanbono/nuclei-templates.git
  - https://github.com/kabilan1290/templates.git
  - https://github.com/medbsq/ncl.git
  - https://github.com/meme-lord/Custom-Nuclei-Templates.git
  - https://github.com/MR-pentestGuy/nuclei-templates.git
  - https://github.com/n1f2c3/mytemplates.git
  - https://github.com/NitinYadav00/My-Nuclei-Templates.git
  - https://github.com/notnotnotveg/nuclei-custom-templates.git
  - https://github.com/obreinx/nuceli-templates.git
  - https://github.com/panch0r3d/nuclei-templates.git
  - https://github.com/peanuth8r/Nuclei_Templates.git
  - https://github.com/pikpikcu/my-nuclei-templates.git
  - https://github.com/pikpikcu/nuclei-templates.git
  - https://github.com/R-s0n/Custom_Vuln_Scan_Templates.git
  - https://github.com/rafaelcaria/Nuclei-Templates.git
  - https://github.com/rahulkadavil/nuclei-templates.git
  - https://github.com/randomstr1ng/nuclei-sap-templates.git
  - https://github.com/redteambrasil/nuclei-templates.git
  - https://github.com/ree4pwn/my-nuclei-templates.git
  - https://github.com/sadnansakin/my-nuclei-templates.git
  - https://github.com/Saimonkabir/Nuclei-Templates.git
  - https://github.com/Saptak9983/Nuclei-Template.git
  - https://github.com/securitytest3r/nuclei_templates_work.git
  - https://github.com/sharathkramadas/k8s-nuclei-templates.git
  - https://github.com/shifa123/detections.git
  - https://github.com/smaranchand/nuclei-templates.git
  - https://github.com/Str1am/my-nuclei-templates.git
  - https://github.com/System00-Security/backflow.git
  - https://github.com/test502git/log4j-fuzz-head-poc.git
  - https://github.com/thebrnwal/Content-Injection-Nuclei-Script.git
  - https://github.com/thelabda/nuclei-templates.git
  - https://github.com/yavolo/nuclei-templates.git
  - https://github.com/z3bd/nuclei-templates.git
  - https://github.com/zinminphyo0/KozinTemplates.git